repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.8
    hooks:
        - id: pymarkdown
          args:
              - --disable-rules
              - line-length
              - scan
  # fix this later I was getting an error
  # TypeError: set object expected; got list
  # and there's some ongoing discussion about it
  # - repo: https://github.com/adamchainz/blacken-docs
  #   rev: v1.12.0
  #   hooks:
  #     - id: blacken-docs
  #       additional_dependencies:
  #         - black==23.1.0
