name: Ruff

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches: [main]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: python -Im pip install --user ruff==0.5.0

    - name: Run ruff
      run: ruff check --output-format=github wagtail_footnotes
